id: I7850CC9C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T04:50:24+00:00'
last_modified: '2022-06-07T21:27:12.979918+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1617
  title: བཻ་ཌཱུརྱ་དཀར་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3166':
      image_group_id: I1KG1710
      title: ''
      total_pages: 1268
      order: 1
      base_file: 3166.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
