id: P004255
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG1617
  title: བཻ་ཌཱུརྱ་དཀར་པོ།
  author: ''
  volumes:
    11b8872808714aa3be8320cdf37e5bdf:
      image_group_id: I1KG1710
      title: ''
      volume_number: 1
      total_pages: 1268
      base_file: v001.txt
